### ISSUE TITLE
Add TypeScript interfaces

### ISSUE THREAD

**Issue by fox1t** [HospitalRun/hospitalrun#182]
## 🚀 Feature Proposal

We need TS interfaces, alongside JSONSchemas, for better developer experience. The interfaces will be derived directly from Schemas. 

## Motivation

Please outline the motivation for the proposal.

## TODO:
- [ ] rename model to models
- [ ] add one folder per model
- [ ] add a proper TS interface for every model
- [ ] export default the interface
- [ ] export JSONSchema as schema
